services:
  orderprocessingservice:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5136:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ..
        target: /workspace
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
