name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  orderprocessingservice:
    runs-on: ubuntu-latest
    name: Build OrderProcessingService
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore OrderProcessingService/OrderProcessingService.csproj

      - name: Build project
        run: dotnet build OrderProcessingService/OrderProcessingService.csproj -c Release --no-restore
